//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisonVoiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintenance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public maintenance()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int idMaintenance { get; set; }
        public Nullable<System.DateTime> dateMintenance { get; set; }
        public string description { get; set; }
        public Nullable<int> idVoiture { get; set; }
        public string idClient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
