//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisonVoiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int idEmployee { get; set; }
        public string nomCompletEmp { get; set; }
        public Nullable<System.DateTime> dateNaissance { get; set; }
        public string adresse { get; set; }
        public string numberPhone { get; set; }
        public Nullable<int> idspecialites { get; set; }
    
        public virtual specialite specialite { get; set; }
    }
}
